# Generated by Django 5.1.3 on 2024-11-06 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_production', models.CharField(max_length=4)),
                ('door_quantity', models.IntegerField()),
                ('cilindrada', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehiculos_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km', models.IntegerField(default=0)),
                ('body_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.bodywork')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.brand')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.condition')),
                ('country_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.country')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.fuel')),
                ('gama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.gama')),
                ('model_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.modelo')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='vehiculos.transmission')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehiculos.car')),
            ],
        ),
    ]
