# Generated by Django 5.1.2 on 2024-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculoreview',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='vehiculoreview',
            name='text',
            field=models.TextField(verbose_name='Texto de la reseña'),
        ),
    ]
